"""Audio sources — where blocks of samples come from.

The decoder never cares which of these it is fed, so early development runs
entirely on `SyntheticCWSource` / `WavFileSource` with no hardware. When a real
interface is available, `SoundDeviceSource` slots in unchanged.
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Iterator
import wave
import numpy as np

from .synth import synthesize_cw


class AudioSource(ABC):
    sample_rate: int

    @abstractmethod
    def blocks(self) -> Iterator[np.ndarray]:
        ...


class ArraySource(AudioSource):
    def __init__(self, audio: np.ndarray, sample_rate: int, block_size: int = 1024):
        self.audio = np.asarray(audio, dtype=np.float32)
        self.sample_rate = sample_rate
        self.block_size = block_size

    def blocks(self) -> Iterator[np.ndarray]:
        for i in range(0, len(self.audio), self.block_size):
            yield self.audio[i:i + self.block_size]


class SyntheticCWSource(ArraySource):
    """Generate CW audio on the fly — the no-hardware development driver."""
    def __init__(self, text: str, wpm: float = 20.0, tone_hz: float = 600.0,
                 sample_rate: int = 8000, snr_db: float | None = None,
                 block_size: int = 1024, seed: int | None = 0):
        r = synthesize_cw(text, wpm=wpm, tone_hz=tone_hz, sample_rate=sample_rate,
                          snr_db=snr_db, seed=seed)
        super().__init__(r.audio, sample_rate, block_size)
        self.truth = r


class WavFileSource(ArraySource):
    """Read a mono/stereo WAV (e.g. exported from GQRX or generated by cwwav)."""
    def __init__(self, path: str, block_size: int = 1024):
        with wave.open(path, "rb") as wf:
            fs = wf.getframerate()
            n = wf.getnframes()
            ch = wf.getnchannels()
            width = wf.getsampwidth()
            raw = wf.readframes(n)
        dtype = {1: np.uint8, 2: np.int16, 4: np.int32}[width]
        data = np.frombuffer(raw, dtype=dtype).astype(np.float32)
        if ch > 1:
            data = data.reshape(-1, ch).mean(axis=1)
        maxv = float(np.iinfo(dtype).max) if dtype != np.uint8 else 255.0
        if dtype == np.uint8:
            data = (data - 128.0) / 128.0
        else:
            data = data / maxv
        super().__init__(data, fs, block_size)


class SoundDeviceSource(AudioSource):
    """Live sound-card input via PortAudio. Requires `pip install sounddevice`
    and a real audio interface, so it's guarded — the rest of the layer runs
    without it."""
    def __init__(self, sample_rate: int = 8000, block_size: int = 1024, device=None):
        self.sample_rate = sample_rate
        self.block_size = block_size
        self.device = device

    def blocks(self) -> Iterator[np.ndarray]:  # pragma: no cover - needs hardware
        try:
            import sounddevice as sd
        except ImportError as e:
            raise RuntimeError(
                "SoundDeviceSource needs the 'sounddevice' package and a real "
                "audio input. Use SyntheticCWSource or WavFileSource for "
                "hardware-free development."
            ) from e
        with sd.InputStream(samplerate=self.sample_rate, channels=1,
                            blocksize=self.block_size, device=self.device) as stream:
            while True:
                data, _ = stream.read(self.block_size)
                yield data[:, 0].astype(np.float32)
