from __future__ import annotations

from django.urls import path

from .api import (
    abbrev,
    eqsl_config,
    live_ingest,
    log_adif,
    log_eqsl_upload,
    log_import,
    log_lookup,
    log_quick,
    macros,
    qrz_config,
    qrz_logbook_sync,
    rig,
    rig_daemon,
    rig_photo,
    rig_setup_data,
    rig_tx,
    sim_control,
)
from .views import (
    CallbookView,
    CWSessionCRUDView,
    DecodeView,
    LiveView,
    LogbookCRUDView,
    MonitorView,
    RigSetupView,
    SendView,
    SimulatorView,
    session_audio,
)

urlpatterns = [
    path("cw/", MonitorView.as_view(), name="cw-monitor"),
    path("cw/live/", LiveView.as_view(), name="cw-live"),
    path("cw/live/ingest/", live_ingest, name="cw-live-ingest"),
    path("cw/sim/", SimulatorView.as_view(), name="cw-sim"),
    path("cw/sim/control/", sim_control, name="cw-sim-control"),
    path("cw/macros/", macros, name="cw-macros"),
    path("cw/abbrev/", abbrev, name="cw-abbrev"),
    path("cw/log/quick/", log_quick, name="cw-log-quick"),
    path("cw/log/adif/", log_adif, name="cw-log-adif"),
    path("cw/log/qrz/", qrz_config, name="cw-log-qrz"),
    path("cw/callbook/", CallbookView.as_view(), name="cw-callbook"),
    path("cw/callbook/sync/", qrz_logbook_sync, name="cw-qrz-logbook"),
    path("cw/log/import/", log_import, name="cw-log-import"),
    path("cw/log/lookup/", log_lookup, name="cw-log-lookup"),
    path("cw/log/eqsl/", log_eqsl_upload, name="cw-log-eqsl"),
    path("cw/log/eqsl/config/", eqsl_config, name="cw-log-eqsl-config"),
    *LogbookCRUDView.get_urls(),
    path("cw/rig/", rig, name="cw-rig"),
    path("cw/rig/tx/", rig_tx, name="cw-rig-tx"),
    path("cw/rig/setup/", RigSetupView.as_view(), name="cw-rig-setup"),
    path("cw/rig/setup/data/", rig_setup_data, name="cw-rig-setup-data"),
    path("cw/rig/setup/photo/", rig_photo, name="cw-rig-photo"),
    path("cw/rig/daemon/", rig_daemon, name="cw-rig-daemon"),
    path("cw/decode/", DecodeView.as_view(), name="cw-decode"),
    path("cw/send/", SendView.as_view(), name="cw-send"),
    path("cw/sessions/<int:pk>/audio.wav", session_audio, name="cw-session-audio"),
    *CWSessionCRUDView.get_urls(),
]
