# Generated by Django 6.0.7 on 2026-08-05 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CWSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('rx', 'Received'), ('tx', 'Sent')], max_length=2)),
                ('source', models.CharField(choices=[('synth', 'Practice (synthesized)'), ('wav', 'WAV upload'), ('text', 'Composed message')], max_length=8)),
                ('text', models.TextField(help_text='Decoded copy (rx) or composed message (tx)')),
                ('truth', models.TextField(blank=True, help_text='Ground-truth text for practice decodes')),
                ('wpm', models.FloatField(default=0.0)),
                ('tone_hz', models.FloatField(default=600.0)),
                ('snr_db', models.FloatField(blank=True, null=True)),
                ('callsigns', models.JSONField(blank=True, default=list)),
                ('telemetry', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cw_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CW Session',
                'verbose_name_plural': 'CW Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
