# Generated by Django 6.0.7 on 2026-08-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cwsession',
            name='source',
            field=models.CharField(choices=[('synth', 'Practice (synthesized)'), ('wav', 'Recording upload'), ('text', 'Composed message')], max_length=8),
        ),
    ]
