# Generated by Django 6.0.7 on 2026-08-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw', '0002_alter_cwsession_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cwsession',
            name='source',
            field=models.CharField(choices=[('synth', 'Practice (synthesized)'), ('wav', 'Recording upload'), ('text', 'Composed message'), ('live', 'Live monitor')], max_length=8),
        ),
    ]
