# Generated by Django 6.0.7 on 2026-08-05 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw', '0003_alter_cwsession_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CWSimControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noise_level', models.FloatField(default=0.08, help_text='Band static level (0–0.5)')),
                ('input_gain', models.FloatField(default=1.0, help_text='Input level multiplier (0.1–10)')),
                ('squelch_db', models.FloatField(default=3.0, help_text="SNR gate in dB; below it the key can't open (0 = off)")),
                ('afc', models.BooleanField(default=True, help_text='Automatic frequency control — chase the strongest carrier')),
                ('paused_signals', models.BooleanField(default=False, help_text='Static only — stop scheduling stations')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cw_sim_control', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CW Simulator Control',
            },
        ),
    ]
