# Generated by Django 6.0.7 on 2026-08-05 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw', '0004_cwsimcontrol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CWMacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='The /command — lowercase, no spaces (e.g. cq, 73, rst)', max_length=24)),
                ('text', models.CharField(help_text='Message to key. Placeholders: {call} {mycall} {rst} — or your own.', max_length=280)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cw_macros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CW Macro',
                'ordering': ['order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_macro_per_user')],
            },
        ),
    ]
