# Generated by Django 6.0.7 on 2026-08-05 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw', '0005_cwmacro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CWRig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('host', models.CharField(default='127.0.0.1', max_length=200)),
                ('port', models.PositiveIntegerField(default=4532)),
                ('use_ptt', models.BooleanField(default=True, help_text="Key PTT via CAT. Off = rely on the rig's VOX.")),
                ('audio_output', models.CharField(blank=True, help_text='Output sound device name/index for TX audio (blank = system default)', max_length=200)),
                ('ptt_lead_ms', models.PositiveIntegerField(default=150, help_text="Delay between PTT-on and audio so the first dit isn't clipped")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cw_rig', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CW Rig',
            },
        ),
    ]
