# Generated by Django 6.0.7 on 2026-08-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw', '0006_cwrig'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwrig',
            name='baud',
            field=models.PositiveIntegerField(default=115200),
        ),
        migrations.AddField(
            model_name='cwrig',
            name='rig_model',
            field=models.PositiveIntegerField(blank=True, help_text='Hamlib rig model number (rigctl -l)', null=True),
        ),
        migrations.AddField(
            model_name='cwrig',
            name='serial_port',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
