# Generated by Django 6.0.7 on 2026-08-06 20:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw', '0007_cwrig_baud_cwrig_rig_model_cwrig_serial_port'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRZProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=64)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qrz_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QSO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call', models.CharField(db_index=True, max_length=20)),
                ('when', models.DateTimeField(default=django.utils.timezone.now)),
                ('freq_mhz', models.FloatField(blank=True, null=True)),
                ('band', models.CharField(blank=True, max_length=8)),
                ('mode', models.CharField(default='CW', max_length=12)),
                ('rst_sent', models.CharField(blank=True, default='599', max_length=8)),
                ('rst_rcvd', models.CharField(blank=True, max_length=8)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('qth', models.CharField(blank=True, max_length=120)),
                ('gridsquare', models.CharField(blank=True, max_length=8)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('comment', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('session', 'From session'), ('reply', 'On-air reply')], default='manual', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qsos', to='cw.cwsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qsos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QSO',
                'verbose_name_plural': 'QSOs',
                'ordering': ['-when'],
            },
        ),
    ]
