# Generated by Django 6.0.7 on 2026-08-06 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw', '0008_qrzprofile_qso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qso',
            name='eqsl_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qrzprofile',
            name='password',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='qso',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('session', 'From session'), ('reply', 'On-air reply'), ('import', 'ADIF import')], default='manual', max_length=8),
        ),
        migrations.CreateModel(
            name='EQSLProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=64)),
                ('password', models.CharField(blank=True, max_length=512)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eqsl_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
