# Generated by Django 6.0.7 on 2026-08-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw', '0009_qso_eqsl_sent_at_alter_qrzprofile_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrzprofile',
            name='logbook_key',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='qso',
            name='qrz_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
