# Generated by Django 6.0.7 on 2026-08-08 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.cw.models


class Migration(migrations.Migration):

    dependencies = [
        ('cw', '0010_qrzprofile_logbook_key_qso_qrz_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CWRigPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rig_model', models.PositiveIntegerField(help_text='Hamlib rig model number (rigctl -l)')),
                ('image', models.ImageField(upload_to=apps.cw.models._rig_photo_path)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cw_rig_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CW Rig Photo',
                'constraints': [models.UniqueConstraint(fields=('user', 'rig_model'), name='uniq_rig_photo_per_user_model')],
            },
        ),
    ]
