# Generated by Django 6.0.7 on 2026-08-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw', '0011_cwrigphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwrig',
            name='callsign',
            field=models.CharField(blank=True, help_text='Your station callsign. Fills {mycall} in send macros and the ADIF STATION_CALLSIGN. Blank = fall back to your username.', max_length=20),
        ),
    ]
