# Generated by Django 6.0.7 on 2026-08-08 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw', '0012_cwrig_callsign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CWVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='The {tag} — lowercase, no spaces (e.g. rig, ant, qth)', max_length=24)),
                ('value', models.CharField(help_text='What {tag} expands to', max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cw_variables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CW Variable',
                'ordering': ['order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_variable_per_user')],
            },
        ),
    ]
