# Generated by Django 6.0.7 on 2026-08-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw', '0013_cwvariable'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwrig',
            name='send_tone_hz',
            field=models.PositiveSmallIntegerField(default=600),
        ),
        migrations.AddField(
            model_name='cwrig',
            name='send_wpm',
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
