# Generated by Django 6.1 on 2026-08-29 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw', '0014_cwrig_send_tone_hz_cwrig_send_wpm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What to call it on the strip (e.g. WXYZ, Jazz)', max_length=32)),
                ('freq_mhz', models.FloatField(help_text='Frequency in MHz (FM broadcast: 88–108)')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radio_stations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Radio Station',
                'ordering': ['order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_radio_station_per_user')],
            },
        ),
    ]
