# Generated by Django 6.1 on 2026-08-29 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw', '0015_radiostation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AntennaSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antenna', models.CharField(help_text="What was connected — 'stock whip', 'dipole', 'loop'", max_length=60)),
                ('gain_db', models.FloatField(default=40.0, help_text='Tuner gain, pinned so runs compare')),
                ('results', models.JSONField(default=list, help_text='Per-band scores from the sweep')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antenna_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Antenna Survey',
                'ordering': ['-created_at'],
            },
        ),
    ]
