# Generated by Django 6.1 on 2026-08-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw', '0016_antennasurvey'),
    ]

    operations = [
        migrations.AddField(
            model_name='antennasurvey',
            name='device',
            field=models.CharField(blank=True, help_text="Which SDR took the run — two dongles aren't comparable", max_length=120),
        ),
    ]
