"""Audio sources — where blocks of samples come from.

The decoder never cares which of these it is fed, so early development runs
entirely on `SyntheticCWSource` / `WavFileSource` with no hardware. When a real
interface is available, `SoundDeviceSource` slots in unchanged.
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from typing import BinaryIO, Iterator

import numpy as np

from .manager import FloatArray
from .synth import synthesize_cw
from .wav import float32_from_wav


class AudioSource(ABC):
    sample_rate: int

    @abstractmethod
    def blocks(self) -> Iterator[FloatArray]: ...


class ArraySource(AudioSource):
    def __init__(self, audio: FloatArray, sample_rate: int, block_size: int = 1024) -> None:
        self.audio: FloatArray = np.asarray(audio, dtype=np.float32)
        self.sample_rate = sample_rate
        self.block_size = block_size

    def blocks(self) -> Iterator[FloatArray]:
        for i in range(0, len(self.audio), self.block_size):
            yield self.audio[i : i + self.block_size]


class SyntheticCWSource(ArraySource):
    """Generate CW audio on the fly — the no-hardware development driver."""

    def __init__(
        self,
        text: str,
        wpm: float = 20.0,
        tone_hz: float = 600.0,
        sample_rate: int = 8000,
        snr_db: float | None = None,
        block_size: int = 1024,
        seed: int | None = 0,
    ) -> None:
        r = synthesize_cw(
            text, wpm=wpm, tone_hz=tone_hz, sample_rate=sample_rate,
            snr_db=snr_db, seed=seed,
        )
        super().__init__(r.audio, sample_rate, block_size)
        self.truth = r


class WavFileSource(ArraySource):
    """Read a mono/stereo WAV (e.g. exported from GQRX or generated by cwwav)."""

    def __init__(self, path_or_stream: str | BinaryIO, block_size: int = 1024) -> None:
        if isinstance(path_or_stream, str):
            with open(path_or_stream, "rb") as f:
                data, fs = float32_from_wav(f)
        else:
            data, fs = float32_from_wav(path_or_stream)
        super().__init__(data, fs, block_size)


class SoundDeviceSource(AudioSource):
    """Live sound-card input via PortAudio. Requires `pip install sounddevice`
    and a real audio interface, so it's guarded — the rest of the layer runs
    without it."""

    def __init__(
        self, sample_rate: int = 8000, block_size: int = 1024, device: int | str | None = None
    ) -> None:
        self.sample_rate = sample_rate
        self.block_size = block_size
        self.device = device

    def blocks(self) -> Iterator[FloatArray]:  # pragma: no cover - needs hardware
        try:
            import sounddevice as sd
        except ImportError as e:
            raise RuntimeError(
                "SoundDeviceSource needs the 'sounddevice' package and a real "
                "audio input. Use SyntheticCWSource or WavFileSource for "
                "hardware-free development."
            ) from e
        with sd.InputStream(
            samplerate=self.sample_rate, channels=1,
            blocksize=self.block_size, device=self.device,
        ) as stream:
            while True:
                data, _ = stream.read(self.block_size)
                yield data[:, 0].astype(np.float32)
